### ISSUE TITLE
Create account should fund the new account with 1 hbar as default.

### ISSUE THREAD

**Issue by sreejithkaimal** [hashgraph/hedera-wallet-android#119]
<a href="https://github.com/donaldthibeau"><img src="https://avatars2.githubusercontent.com/u/42808726?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [donaldthibeau](https://github.com/donaldthibeau)**
_Tuesday Sep 24, 2019 at 13:44 GMT_
_Originally opened as https://github.com/swirlds/clients-hedera/issues/813_

----

Add user notification: "Verify control over the new account before transferring more hbar. The account owner should attempt to transfer hbar to verify account control."

**Comment by avichalsaxena** [comment]
This was referenced in the latest build 129.
