### ISSUE TITLE
List library licenses

### ISSUE THREAD

**Issue by sreejithkaimal** [hashgraph/hedera-wallet-android#124]
<a href="https://github.com/robert-at-hedera"><img src="https://avatars0.githubusercontent.com/u/55102434?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [robert-at-hedera](https://github.com/robert-at-hedera)**
_Friday Oct 04, 2019 at 16:11 GMT_
_Originally opened as https://github.com/swirlds/clients-hedera/issues/843_

----

Libraries used by the app under the MIT, Apache, and similar licenses require attribution.  This needs to happen "in" the release, which is where these libraries actually are used.  A license screen accessible from the about screen is sufficient for the latter.

The task is to go through each app, Android and iOS, and determine what libraries are used.  Gather the licenses and put them into a text file.  Then add a button to the about screen linking to a new license screen which simply displays the text file.

**Comment by sreejithkaimal** [comment]
<a href="https://github.com/steven-sheehy"><img src="https://avatars3.githubusercontent.com/u/17552371?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [steven-sheehy](https://github.com/steven-sheehy)**
_Friday Oct 04, 2019 at 16:21 GMT_

----

For maven apps, you can add the `license-maven-plugin` and run `mvn license:license-list` and `mvn license:download-licenses` to help automate this.

**Comment by sreejithkaimal** [comment]
<a href="https://github.com/robert-at-hedera"><img src="https://avatars0.githubusercontent.com/u/55102434?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [robert-at-hedera](https://github.com/robert-at-hedera)**
_Friday Oct 04, 2019 at 16:33 GMT_

----

That's a very good point for Android, thanks Steve!

On iOS, apparently Cocoapods can do something similar.  There's information at this link suggesting adding licenses automatically under the Settings app via a plist.
https://github.com/CocoaPods/CocoaPods/wiki/Acknowledgements

**Comment by sreejithkaimal** [comment]
<a href="https://github.com/avichalsaxena"><img src="https://avatars2.githubusercontent.com/u/40248431?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [avichalsaxena](https://github.com/avichalsaxena)**
_Monday Oct 21, 2019 at 13:26 GMT_

----

For iOS, these are the licenses that I found. Please review them @robert-at-hedera .
[ios-lib-licenses.zip](https://github.com/swirlds/clients-hedera/files/3751005/ios-lib-licenses.zip)

**Comment by sreejithkaimal** [comment]
<a href="https://github.com/avichalsaxena"><img src="https://avatars2.githubusercontent.com/u/40248431?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [avichalsaxena](https://github.com/avichalsaxena)**
_Tuesday Oct 22, 2019 at 18:04 GMT_

----

For Android, these are the licenses. Please review them @robert-at-hedera 
[open_source_licenses.html.zip](https://github.com/swirlds/clients-hedera/files/3757594/open_source_licenses.html.zip)

**Comment by robert-at-hedera** [comment]
Sadly I did not get far in the Android list today.  For whatever reason the gradle output seems to be wrong, and I have no idea how to fix that.  (I got very similar results to Avichal.)  I will need to collect the licenses manually.
