### ISSUE TITLE
Unit Testing Cases added

### ISSUE THREAD

**Issue by sreejithkaimal** [hashgraph/hedera-wallet-android#133]
<a href="https://github.com/avichalsaxena"><img src="https://avatars2.githubusercontent.com/u/40248431?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [avichalsaxena](https://github.com/avichalsaxena)**
_Wednesday Oct 23, 2019 at 13:48 GMT_
_Originally opened as https://github.com/swirlds/clients-hedera/pull/856_

----

----

_**[avichalsaxena](https://github.com/avichalsaxena)** included the following code: https://github.com/swirlds/clients-hedera/pull/856/commits_

**Comment by avichalsaxena** [comment]
Duplicate see #122
