### ISSUE TITLE
All the records show as UNKNOWN.

### ISSUE THREAD

**Issue by avichalsaxena** [hashgraph/hedera-wallet-android#137]
![Screenshot_1572442830](https://user-images.githubusercontent.com/40248431/67862927-5a485000-faf9-11e9-9914-ee607fe9a566.png)

**Comment by sreejithkaimal** [comment]
Even after providing a Name to the account, it still shows as unknown.

**Comment by avichalsaxena** [comment]
Tested again. Bug is resolved.
