### ISSUE TITLE
Refresh button on nodes is not working.

### ISSUE THREAD

**Issue by avichalsaxena** [hashgraph/hedera-wallet-android#138]
After disabling some of the nodes, when refresh is pressed. It should refresh the nodes list. Seems even after doing so, the old nodes remain as it is.

**Comment by sreejithkaimal** [comment]
delta is not updated, the disabled Nodes are not removed. Random node IP is not cleared

**Comment by avichalsaxena** [comment]
@surendrapatidar After the recent commits, the refresh button is working. But If I enter Garbage value in the add nodes, there should be an error saying "Please enter a valid IP Address"
