### ISSUE TITLE
On entering wrong account ID on accountViewerScreen, should show an error.

### ISSUE THREAD

**Issue by avichalsaxena** [hashgraph/hedera-wallet-android#139]
When user Adds an Account on account viewer screen, if the account ID is wrong, there is no error message on the screen. There should be an error screen, which says "Please enter a valid account ID"

**Comment by sreejithkaimal** [comment]
![IMG_6463](https://user-images.githubusercontent.com/41587635/67872231-0e50d780-fb08-11e9-972a-cd59f6c2b3da.jpg)

**Comment by avichalsaxena** [comment]
Tested. Bug solved in latest commits.
