### ISSUE TITLE
Left view after adding an account, Default Account should change to the account name entered as it does in iOS.

### ISSUE THREAD

**Issue by avichalsaxena** [hashgraph/hedera-wallet-android#141]
![Screenshot_1572444936](https://user-images.githubusercontent.com/40248431/67865960-97631100-fafe-11e9-8219-78cbcf29baa3.png)

![Simulator Screen Shot - iPhone 11 - 2019-10-30 at 10 15 41](https://user-images.githubusercontent.com/40248431/67865793-4b17d100-fafe-11e9-8ca0-2f447563f09c.png)

**Comment by sreejithkaimal** [comment]
@avichalsaxena Please kill the app and try again, if it works just update this.
