### ISSUE TITLE
Allow Android to build without app.properties

### ISSUE THREAD

**Issue by robert-at-hedera** [hashgraph/hedera-wallet-android#153]
Currently no one outside of Hedera can build the Android app because they do not have our app.properties file, which contains our Branch keys.  For this issue, branch can be disabled universally but need not be removed completely from the code base.

**Comment by dimitrileite** [comment]
Can we make then another branch, a public one?

**Comment by robert-at-hedera** [comment]
We aren't really using branch.io at this point, so instead I'm just removing it.
