### ISSUE TITLE
Update address book to include new nodes - Android

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-wallet-android#157]

**Comment by robert-at-hedera** [comment]
Pausing this issue in favor of iOS issue 237 investigation.

I have written out two key "update" paths in addition to the clean install scenario; these are the three primary use cases for this issue.  A fourth use case is for persons who have modified their node list, and this is of lesser concern.

1. Clean Install
2. Node update via "channel", i.e. the store
3. Node update via manual network request
4. (Lower priority) Note update via channel when node list was modified

Current behavior means that cases 1, 3, and 4 will function correctly; case 2 will not result in an update.

The node list is loaded from file if and only if the database contains no nodes.  This can occur in two cases: first, a fresh install; second, if all nodes are deleted by the user.

Going forward, I intend to track multiple networks internally and the source of their nodes.  Updated files will load additional node information, and the current node list may or may not be updated depending on the update procedure.  In the simplest case, a file-sourced list will be replaced with a newer file-sourced list.  In another case, if nodes have been customized manually, no update will occur.  The procedure for updating a network-sourced list is pending consideration.

Given that process, we actually only retain case 1.  The current list of nodes are of an unknown source.  Updating the unknown source list to be of a known source is a one-time process executed during a database migration.

To support cases 2 and 4, we need to compare the nodes to a prior node list to determine the node list source.  If the current list is exactly the prior list, then mark the current list as sourced from a file.  If the current list is a subset of the prior list or contains nodes not in the new and prior lists, then assume the list was manually entered by the user.

We finally consider case 3.  If the current list is a superset of the prior nodes and a subset of the new nodes, then assume the list was updated from the network recently and use the file-sourced list.

I probably need to put together a design document for this change and get it reviewed.

Anyway, I am currently in progress implementing this design.  I am currently setting up the new tables and ORM objects.

**Comment by robert-at-hedera** [comment]
I've put together a low-level design document.  I need to sleep on it and make modifications in the morning before sending it out.

Another item is to itemize the work items, particularly the very vague tests, so that I can give a proper work estimate.  It'll still be horribly wrong, but it's time to get back in practice.

**Comment by robert-at-hedera** [comment]
Saved change off locally.  The PR will need to include the actual address book change(s) to operate correctly.
