### ISSUE TITLE
Master Reset does not remove  key generated with previous recovery phrase.

### ISSUE THREAD

**Issue by noshmody** [hashgraph/hedera-wallet-android#195]
Master Reset does not remove  key generate with previous recovery phrase.
Reported by Ronald Kreider in [YouTube Video](https://youtu.be/EEoSBnbd_Mw)
Steps to reproduce
1st Create a new account -> 1st Recovery Phrase and key for an account
Master Reset (should have removed all traces of earlier account creation)
2nd Create a new account -> 2nd Recovery Phrase (unique). **_Key for an account is identical to key created by 1 Recovery Phrase_**  

- [ ] Reproduce and identify cause
- [ ] Fix

**Comment by anighanta** [comment]
I think I found the bug. 

When we are creating a new master wallet, 
https://github.com/hashgraph/hedera-wallet-android/blob/b717484a0b37291b6975369830344f8855aaae51/app/src/main/java/hedera/hgc/hgcwallet/database/DBHelper.kt#L50

We always pick the first one from the available wallets, if none present we create a new one. 

When we do a MasterRest we are supposed to clean all databases in that we use. That would ensure that when creating a master wallet again we don't get any previously created wallets. 

We clear the databases on Reset here https://github.com/hashgraph/hedera-wallet-android/blob/b717484a0b37291b6975369830344f8855aaae51/app/src/main/java/hedera/hgc/hgcwallet/database/AppDatabase.kt#L64

This `Android Room` method needs time to clear the databases according to [this](https://stackoverflow.com/questions/49573607/clearalltables-doesnt-work)

Forcing a WAL checkpoint on the database on Reset might help us. 

Also, can we try to test this scenario with a bit delay between resetting and creating a new wallet ?
@donaldthibeau 

And we would need `app.properties` file to build a new version. @donaldthibeau can you please reach out to Robert and see if can get it soon.
