### ISSUE TITLE
Tag Android Wallet Releases

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-wallet-android#198]
Version | Commit Id
------------ | -------------
1.4.136 | 
1.3.131 | [61f5c13fd5910a999bcb2823b0f150f09807ce67](https://github.com/hashgraph/hedera-wallet-android/commit/61f5c13fd5910a999bcb2823b0f150f09807ce67)
1.3.129 | [e0dc3a8410629a91777af910519364ef157e5a30](https://github.com/swirlds/clients-hedera/commit/e0dc3a8410629a91777af910519364ef157e5a30)
1.2.125 | [5620a23d13db4fef01545c5c63777e055d8d8bc0](https://github.com/swirlds/clients-hedera/commit/5620a23d13db4fef01545c5c63777e055d8d8bc0)
1.2.118 | 
1.2 | 
1.2 | 
1.1.1 | [b2b6fc56c87ac350ff6268599409bdb9e3dfc660](https://github.com/swirlds/clients-hedera/commit/b2b6fc56c87ac350ff6268599409bdb9e3dfc660)
1.1 | [20c0b1dee82b2ce2f399618aab0f168092db997b](https://github.com/swirlds/clients-hedera/commit/20c0b1dee82b2ce2f399618aab0f168092db997b#diff-48ee046028069a9c6ded9844911eab9020389ac067e2a8772244b99be182e063)
1.1.0 | [e58fbdd5ba5f8369aaf0d7d2032b37f29ef7d487](https://github.com/swirlds/clients-hedera/commit/e58fbdd5ba5f8369aaf0d7d2032b37f29ef7d487)
1.1.0 | [cf8a1ca1de159a1db77a7e0c094a15f971282400](https://github.com/swirlds/clients-hedera/commit/cf8a1ca1de159a1db77a7e0c094a15f971282400)
1.0.3 | [d727eb4a49c1bb88477ad0bd88ef882690055777](https://github.com/swirlds/clients-hedera/commit/d727eb4a49c1bb88477ad0bd88ef882690055777)
1.0.2 | [82ce65e1eda6a8a02258d04706794f9978cee126](https://github.com/swirlds/clients-hedera/commit/82ce65e1eda6a8a02258d04706794f9978cee126)
1.0.1 | [1108ca0d6c2eff2e00c0c17303c18bc94f3c676c](https://github.com/swirlds/clients-hedera/commit/1108ca0d6c2eff2e00c0c17303c18bc94f3c676c)

**Comment by anighanta** [comment]
@kenthejr @donaldthibeau Im gonna tag these commits respectively with their release versions. Let me know if I need to change anything.

**Comment by donaldthibeau** [comment]
Looks good to me.

**Comment by anighanta** [comment]
Done tagging.
repo - [hedera-wallet-android](https://github.com/hashgraph/hedera-wallet-android/tags)
repo - [clients-hedera](https://github.com/swirlds/clients-hedera/tags)
